
spring:
  application:
    name: hms-service
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
  zipkin:
    base-url: http://localhost:9411
#    base-url: http://zipkin-server/
#    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1

server:
  port: 9001
  servlet:
    context-path: /hms

eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      ,http://peer2:8762/eureka/,http://peer3:8763/eureka/

#management:
#  endpoint:
#    health:
#      show-details: always #健康情况-展示全部详情，否则只展示status信息

hms:
  config: test1122
